// Backend "brain" — same API the web client uses. One base, override with
// VITE_API_BASE (see .env.example). The future is: photos -> avatar here too.
export const API_BASE =
  (import.meta.env.VITE_API_BASE as string) || "http://127.0.0.1:8100";

export const avatarUrl = (name: string) => `${API_BASE}/avatars/${name}`;
export const wardrobeUrl = (rel: string) => `${API_BASE}/wardrobe/${rel}`;

// Built animation library. The clips ship inside one "animated avatar" GLB
// (only the meta_male export exists today); the avatar plays them on itself via
// an AnimationMixer that retargets the shared CC_Base_* skeleton by name.
// .mobile.glb = meshopt-compressed build (~28MB vs 88MB), regenerated by the
// backend's scripts/optimize_mobile_glbs.cmd.
export const clipsUrl = () => `${API_BASE}/animations/exports/avatar_animated_meta_male.mobile.glb`;

export type Animation = {
  id: string;
  category: string;
  description: string;
  loop: boolean;
};

export async function fetchAnimations(): Promise<Animation[]> {
  const r = await fetch(`${API_BASE}/animations`);
  if (!r.ok) throw new Error(`animations ${r.status}`);
  return r.json();
}

// Default avatar bases the backend serves. The meta bases are the
// meshopt-compressed mobile builds (~6MB vs 54MB); the realistic bases have no
// mobile build yet (unused by this app's flows).
export const AVATARS = {
  meta_male: "sandbox_meta_male.mobile.glb",
  meta_female: "sandbox_meta_female.mobile.glb",
  male: "sandbox_male.glb",
  female: "sandbox_female.glb",
} as const;

export type WardrobeItem = {
  id: string;
  slot: string;
  label: string;
  thumb: string; // e.g. "clothes/hoodie/thumbnail.png"
  file: string;
  attach_type: "bone" | "skinned";
  attach_to?: string; // bone name for bone-attached items
  // per-style fit for the meta/toon head (glb swap and/or offset+scale nudge)
  styles?: { meta?: { glb?: string; offset?: [number, number, number]; scale?: number } };
};
export type Catalog = {
  slots: Record<string, { label: string; tab?: string }>;
  items: WardrobeItem[];
};

export async function fetchCatalog(): Promise<Catalog> {
  const r = await fetch(wardrobeUrl("catalog.json"));
  if (!r.ok) throw new Error(`catalog ${r.status}`);
  return r.json();
}

/* ---- voice conversation (all OpenAI work happens on the backend) -------- */
export type Msg = { role: "user" | "assistant"; content: string };

async function post(path: string, body: unknown) {
  const r = await fetch(`${API_BASE}${path}`, {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error((await r.json().catch(() => null))?.detail || `${path} ${r.status}`);
  return r;
}

export const chat = (message: string, history: Msg[], language?: string) =>
  post("/chat", { message, history, language }).then((r) => r.json()).then((d) => d.reply as string);

/** Text -> spoken audio as raw bytes (decoded via Web Audio for lip-sync). */
export const speakBuffer = (text: string, voice?: string) =>
  post("/tts", { text, voice }).then((r) => r.arrayBuffer());

/** Recorded audio -> transcript (Whisper on the backend). `lang` is an
 *  ISO-639-1 hint that improves accuracy for non-English speech. */
export async function transcribe(blob: Blob, lang?: string): Promise<string> {
  // Whisper picks the decoder from the filename extension, so match the actual
  // recording format (Chrome: webm, Safari: mp4) instead of hardcoding webm.
  const ext = /mp4|mpeg|m4a/.test(blob.type) ? "mp4" : /ogg/.test(blob.type) ? "ogg" : "webm";
  const fd = new FormData();
  fd.append("audio", blob, `clip.${ext}`);
  if (lang) fd.append("language", lang);
  const r = await fetch(`${API_BASE}/stt`, { method: "POST", body: fd });
  if (!r.ok) throw new Error((await r.json().catch(() => null))?.detail || `stt ${r.status}`);
  return (await r.json()).text as string;
}

// morph definitions (served) -> translate semantic params to shape-key values.
// Same math as the Blender morph_controller / web sandbox: (p-0.5)*2*weight.
type MorphDefs = { params: Record<string, { targets: { shape_key: string; weight: number }[] }> };

export async function morphInfluences(engineParams: Record<string, number>): Promise<Record<string, number>> {
  const defs: MorphDefs = await fetch(`${API_BASE}/data/morph_definitions.json`).then((r) => r.json());
  const out: Record<string, number> = {};
  for (const [name, val] of Object.entries(engineParams)) {
    const spec = defs.params[name];
    if (!spec) continue;
    for (const t of spec.targets) out[t.shape_key] = (out[t.shape_key] || 0) + (val - 0.5) * 2 * t.weight;
  }
  return out;
}

/** Photo -> identity engine params (the "looks like me" analysis). */
export async function analyzePhoto(front: File): Promise<{ gender?: string; engine_params?: Record<string, number> }> {
  const fd = new FormData();
  fd.append("front", front);
  const r = await fetch(`${API_BASE}/analyze?appearance=false`, { method: "POST", body: fd });
  if (!r.ok) throw new Error((await r.json().catch(() => null))?.detail || `analyze ${r.status}`);
  const d = await r.json();
  return { gender: d.parameters?.gender, engine_params: d.engine_params };
}
